### ISSUE TITLE
Uglify not working

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [lautis/uglifier#106]
I'm trying to uglify my ruby on rails project. And inside of this ruby on rails project I have a typescript file with the following code:

```
async function slow() {
  return new Promise(function(resolve, reject) {
      setTimeout(function() {
          console.log("slow finished");
          resolve();
      }, 3000);
  });
}

function fast() {
  console.log("fast");
}

async function run() {
  await slow();
  fast();
}

run();
```

The problem is when I run `RAILS_ENV=production bin/bundle exec rake assets:precompile` I receive this error:

```
rake aborted!
ExecJS::RuntimeError: SyntaxError: Unexpected token operator «*», expected punc «(» (line: 12305, col: 52, pos: 395721)

Error
    at new JS_Parse_Error (/tmp/execjs20170205-13704-1iiu2pkjs:3623:11948)
    at js_error (/tmp/execjs20170205-13704-1iiu2pkjs:3623:12167)
    at croak (/tmp/execjs20170205-13704-1iiu2pkjs:3623:22038)
    at token_error (/tmp/execjs20170205-13704-1iiu2pkjs:3623:22175)
    at expect_token (/tmp/execjs20170205-13704-1iiu2pkjs:3623:22411)
    at expect (/tmp/execjs20170205-13704-1iiu2pkjs:3623:22562)
    at function_ (/tmp/execjs20170205-13704-1iiu2pkjs:3623:27371)
    at expr_atom (/tmp/execjs20170205-13704-1iiu2pkjs:3623:31068)
    at maybe_unary (/tmp/execjs20170205-13704-1iiu2pkjs:3624:1752)
    at expr_ops (/tmp/execjs20170205-13704-1iiu2pkjs:3624:2523)
    at maybe_conditional (/tmp/execjs20170205-13704-1iiu2pkjs:3624:2615)
    at maybe_assign (/tmp/execjs20170205-13704-1iiu2pkjs:3624:3058)
    at expression (/tmp/execjs20170205-13704-1iiu2pkjs:3624:3384)
new JS_Parse_Error ((execjs):3623:11948)
js_error ((execjs):3623:12167)
croak ((execjs):3623:22038)
token_error ((execjs):3623:22175)
expect_token ((execjs):3623:22411)
expect ((execjs):3623:22562)
function_ ((execjs):3623:27371)
expr_atom ((execjs):3623:31068)
maybe_unary ((execjs):3624:1752)
expr_ops ((execjs):3624:2523)
maybe_conditional ((execjs):3624:2615)
maybe_assign ((execjs):3624:3058)
expression ((execjs):3624:3384)
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:21:in `eval'
/var/lib/gems/2.3.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:46:in `call'
/var/lib/gems/2.3.0/gems/uglifier-3.0.4/lib/uglifier.rb:184:in `run_uglifyjs'
/var/lib/gems/2.3.0/gems/uglifier-3.0.4/lib/uglifier.rb:146:in `compile'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:53:in `call'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/var/lib/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/var/lib/gems/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/lib/gems/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/var/lib/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
```

I had installed the [typescript-rails](https://github.com/typescript-ruby/typescript-rails) gem and configured. (It works in development mode `RAILS_ENV=development`, maybe because ufligy is not called).

How could we get this working? How can we transpile to ES7 functions or, how to properly configure uglify to use the real `tsc` compiler?

**Comment by lautis** [comment]
What does your output look like if you don't have Uglifier enabled? The error message points to there being non-ES5 syntax in the output.

As you guessed, the default sprockets setup does not call Uglifier in development environment. There could be other differences as well, so I'd recommend testing without Uglifier but still `RAILS_ENV=production`.

**Comment by lautis** [comment]
In 3.2.0, ES6 support can be enabled with `harmony: true` option. Unfortunately this does not yet include async/await. The progress for that can be followed at https://github.com/mishoo/UglifyJS2/issues/1789
