### ISSUE TITLE
Gem Load Error is: wrong argument type Class (expected Module)

### ISSUE THREAD

**Issue by fabianfrz** [lautis/uglifier#121]
gem cannot be loaded (exits with the following stack trace)
```
There was an error while trying to load the gem 'uglifier'. (Bundler::GemRequireError)
Gem Load Error is: wrong argument type Class (expected Module)
Backtrace for gem load error is:
GEM_PATH/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `include'
GEM_PATH/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
GEM_PATH/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `class_eval'
GEM_PATH/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `block in <top (required)>'
GEM_PATH/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `each'
GEM_PATH/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `<top (required)>'
GEM_PATH/therubyracer-0.12.2/lib/v8.rb:22:in `require'
GEM_PATH/therubyracer-0.12.2/lib/v8.rb:22:in `<top (required)>'
GEM_PATH/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `require'
GEM_PATH/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
GEM_PATH/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
GEM_PATH/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
GEM_PATH/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
GEM_PATH/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
GEM_PATH/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
GEM_PATH/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
GEM_PATH/uglifier-3.2.0/lib/uglifier.rb:5:in `require'
GEM_PATH/uglifier-3.2.0/lib/uglifier.rb:5:in `<top (required)>'
GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:82:in `require'
GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
GEM_PATH/bundler-1.15.3/lib/bundler.rb:108:in `require'
/path/to/beef/core/loader.rb:10:in `<top (required)>'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
./beef:25:in `<main>'
Bundler Error Backtrace:
        from GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:77:in `each'
        from GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:77:in `block in require'
        from GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:66:in `each'
        from GEM_PATH/bundler-1.15.3/lib/bundler/runtime.rb:66:in `require'
        from GEM_PATH/bundler-1.15.3/lib/bundler.rb:108:in `require'
        from /path/to/beef/core/loader.rb:10:in `<top (required)>'
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./beef:25:in `<main>'
```

**Comment by lautis** [comment]
You should update therubyracer to 0.12.3 for Ruby 2.4 compatibility. https://github.com/cowboyd/therubyracer/issues/428

**Comment by fabianfrz** [comment]
@lautis updating the gem file of beef fixes the issue, will report downstream
