### ISSUE TITLE
heroku Uglifier::Error: Name expected

### ISSUE THREAD

**Issue by dcalixto** [lautis/uglifier#134]
After try to deploy a simple rails test app into heroku, in the terminal poped up this 

> Uglifier::Error: Name expected

in the middle of the assets compilation.
i've searched and i did not find anything related to this, so someone ahs any idea this name expected is about?

 

remote:        I, [2018-04-27T20:10:19.341334 #1686]  INFO -- : Writing /tmp/build_171697f13e39a581026e766b205b8f86/public/assets/white-774a5ae6a58216b107623782ce2e1820ebb64f9d294cad32e132c086866f3dd2.png

    remote:        rake aborted!
    remote:        Uglifier::Error: Name expected
    remote:        
/tmp/build_171697f13e39a5810263766b205b8f86/vendor/bundle/ruby/2.3.0/gems/uglifier-4.1.4/lib/uglifier.rb:234:in `parse_result'

**Comment by dcalixto** [comment]
ok, just test locally first.
`bundle exec rake assets:precompile`

**Comment by dcalixto** [comment]
```
ake assets:precompile RAILS_ENV=production --trace
** Invoke assets:precompile (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Invoke environment (first_time)
** Execute environment
** Invoke yarn:install (first_time)
** Execute yarn:install
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Lockfile not saved, no dependencies.
Done in 0.22s.
** Execute assets:precompile
rake aborted!
Uglifier::Error: Name expected
/home/daniel/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/uglifier-4.1.10/lib/uglifier.rb:234:in `parse_result'
/home/daniel/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/uglifier-4.1.10/lib/uglifier.rb:216:in `run_uglifyjs'

```

**Comment by dcalixto** [comment]
sorry my mistake.
